version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://n11857374:EsCIwk1m5E5ZYWWV@n11857374.kerp9zx.mongodb.net/FaceAuth?retryWrites=true&w=majority
      - JWT_SECRET=N11857374_RestAPI
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
